package data;
// Generated 02.03.2018 08:21:53 by Hibernate Tools 4.3.1



/**
 * Benutzer generated by hbm2java
 */
public class Benutzer implements java.io.Serializable {

     private BenutzerId id;
     private Firmenverwaltung firmenverwaltung;
     private String vorname;
     private String nachname;
     private String passwort;
     private String email;
     private boolean admin;
     private boolean newsletter;

    public Benutzer() {
    }

    public Benutzer(BenutzerId id, Firmenverwaltung firmenverwaltung, String vorname, String nachname, String passwort, String email, boolean admin, boolean newsletter) {
       this.id = id;
       this.firmenverwaltung = firmenverwaltung;
       this.vorname = vorname;
       this.nachname = nachname;
       this.passwort = passwort;
       this.email = email;
       this.admin = admin;
       this.newsletter = newsletter;
    }
   
    public BenutzerId getId() {
        return this.id;
    }
    
    public void setId(BenutzerId id) {
        this.id = id;
    }
    public Firmenverwaltung getFirmenverwaltung() {
        return this.firmenverwaltung;
    }
    
    public void setFirmenverwaltung(Firmenverwaltung firmenverwaltung) {
        this.firmenverwaltung = firmenverwaltung;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }
    public String getPasswort() {
        return this.passwort;
    }
    
    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public boolean isNewsletter() {
        return this.newsletter;
    }
    
    public void setNewsletter(boolean newsletter) {
        this.newsletter = newsletter;
    }
}


