package data;
// Generated 02.03.2018 08:21:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Firmenverwaltung generated by hbm2java
 */
public class Firmenverwaltung  implements java.io.Serializable {

     private int idFirmenVerwaltung;
     private Set firmas = new HashSet(0);
     private Set benutzers = new HashSet(0);

    public Firmenverwaltung() {
    }

	
    public Firmenverwaltung(int idFirmenVerwaltung) {
        this.idFirmenVerwaltung = idFirmenVerwaltung;
    }
    public Firmenverwaltung(int idFirmenVerwaltung, Set firmas, Set benutzers) {
       this.idFirmenVerwaltung = idFirmenVerwaltung;
       this.firmas = firmas;
       this.benutzers = benutzers;
    }
   
    public int getIdFirmenVerwaltung() {
        return this.idFirmenVerwaltung;
    }
    
    public void setIdFirmenVerwaltung(int idFirmenVerwaltung) {
        this.idFirmenVerwaltung = idFirmenVerwaltung;
    }
    public Set getFirmas() {
        return this.firmas;
    }
    
    public void setFirmas(Set firmas) {
        this.firmas = firmas;
    }
    public Set getBenutzers() {
        return this.benutzers;
    }
    
    public void setBenutzers(Set benutzers) {
        this.benutzers = benutzers;
    }
}


